# Generated by Django 4.0.6 on 2022-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
        migrations.AddField(
            model_name='room',
            name='participant',
            field=models.CharField(default='anon', max_length=128),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(default='anon', max_length=128),
        ),
    ]
