# Generated by Django 4.0.6 on 2022-08-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_remove_room_online_room_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participant',
        ),
    ]
